// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKR9KiF6XBovzW3uU-W6CApc7FrxqtVVo',
    appId: '1:601240783963:web:cdedddd018fde5f0b8c37e',
    messagingSenderId: '601240783963',
    projectId: 'sias-95c56',
    authDomain: 'sias-95c56.firebaseapp.com',
    storageBucket: 'sias-95c56.appspot.com',
    measurementId: 'G-ZZDWJB96G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGj2XACYPO444eFbgi_nUUCElWuTj5cos',
    appId: '1:601240783963:android:3c8a2fc6dfa6b345b8c37e',
    messagingSenderId: '601240783963',
    projectId: 'sias-95c56',
    storageBucket: 'sias-95c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA901LJS_HF4WzYaKQJm-4r-rLmqzl36I',
    appId: '1:601240783963:ios:b2114bef6449e5c9b8c37e',
    messagingSenderId: '601240783963',
    projectId: 'sias-95c56',
    storageBucket: 'sias-95c56.appspot.com',
    iosBundleId: 'com.example.sias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA901LJS_HF4WzYaKQJm-4r-rLmqzl36I',
    appId: '1:601240783963:ios:8c0f5364893bcb92b8c37e',
    messagingSenderId: '601240783963',
    projectId: 'sias-95c56',
    storageBucket: 'sias-95c56.appspot.com',
    iosBundleId: 'com.example.sias.RunnerTests',
  );
}
